config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  devise_for :users, path: :gurus, path_names: {sign_in: :login, sign_out: :logout},
             controllers: { registrations: 'registrations', sessions: 'sessions' }

  resource :user_badges, only: %i[show]
  resource :badges, only: %i[show]

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, shallow: true, only: %i[show index]
    resources :badges, shallow: true
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feed_backs

end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  ANSWERS_LIMIT_ON_QUESTION = 4

  belongs_to :question
  scope :correct, -> { where(correct: true) }

  validates :text, presence: true
  validate :validate_answers_limit_on_question, on: :create

  private

  def validate_answers_limit_on_question
    errors.add('Answers on question too many') if question.answers.count >= ANSWERS_LIMIT_ON_QUESTION
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges

  enum rule: { success_backend: 'successful_completion_of_all_tests_from_the_Backend_category',
               success_on_first_try: 'passing_the_test_successfully_on_the_first_try',
               success_certain_level: 'successful_completion_of_all_tests_of_a_certain_level'
  }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests
  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/feed_back.rb
class FeedBack < ApplicationRecord
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
require 'date'

class Test < ApplicationRecord
  has_many :test_passages
  has_many :users, through: :test_passages

  belongs_to :category
  has_many :questions, dependent: :destroy

  belongs_to :author, class_name: 'User', foreign_key: :author_id

  scope :by_category_name, ->(category) { joins(:category).where(categories: { title: category }) }

  scope :success_tests, -> { joins(:test_passages).where('test_passages.success = ?', true) }

  def self.by_category_name_arr(category)
    by_category_name(category).order(id: :desc).pluck('tests.title')
  end

  scope :simple_level, -> { where(level: 0..1) }
  scope :average_level, -> { where(level: 2..4) }
  scope :high_level, -> { where(level: 5..Float::INFINITY) }

  scope :by_level, ->(level) { where(level: level) }

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { greater_than_or_equal_to: 1 }

  def timer_on_seconds
    if timer
      dt = timer.to_time
      dt.hour * 3600 + dt.min * 60 + dt.sec
    end
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATE_PERCENT = 85

  belongs_to :user
  belongs_to :test, dependent: :delete
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :next_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def count_questions
    self.test.questions.where("id <= ?", current_question.id).count
  end

  def percentage_result
    100.0 / test.questions.count * correct_questions
  end

  def success?
    percentage_result >= SUCCESS_RATE_PERCENT
  end

  def time_is_left?
    return unless test.timer

    seconds = test.timer_on_seconds
    DateTime.now <= self.created_at + seconds
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first unless self.completed?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         # :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :gists
  has_many :tests, through: :test_passages
  has_many :author_tests, class_name: 'Test', foreign_key: :author_id

  has_many :user_badges
  has_many :badges, through: :user_badges

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end

end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/users_test.rb
class UsersTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :set_badge, only: %i[show destroy edit update ]

  def index
    @badges = Badge.all
  end

  def create
    @badge = current_user.badges.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge), notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :new
    end
  end

  def new
    @badge = Badge.new
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :url_image, :rule)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  def show
    @badges = Badge.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, raise: false
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def this_year
    Date.today.year
  end

  def github_url(author, repo)
    "https://github.com/#{author}/#{repo}"
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feed_backs_helper.rb
module FeedBacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      'Создать вопрос'
    else
      'Редактировать вопрос'
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def display_timer(test)
    test.timer ? test.timer.strftime("%H:%M:%S") : "--:--"
  end
end

app/helpers/user_badges_helper.rb
module UserBadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="title align-middle"><%= badge.title %></td>
  <td class="id align-middle"><img src="<%= badge.url_image %>" width="70" height="70"></td>
  <td class="id align-middle"><%= badge.rule %></td>
  <td class="user_id align-middle">
    <% badge.users.each do |user| %>
      <%= user.email %>
    <% end %>
  </td>
  <td class="functions align-middle"><%= link_to t('.show'), admin_badge_path(badge) %></td>
  <td class="functions align-middle"><%= link_to t('.edit'), edit_admin_badge_path(badge)%></td>
  <td class="functions align-middle">
    <%= link_to t('.delete'), admin_badge_path(badge), method: :delete, data: { confirm: t('.confirm') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<div class="card border-primary">
  <div class="card-body">
    <%= form_with model: [:admin, @badge], local: true do |form| %>
      <%= render 'shared/errors', resource: @badge%>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, id: :badge_title, class: 'form-control' %>

        <%= form.label :url_image %>
        <%= form.text_field :url_image, id: :badge_url_image, class: 'form-control' %>

        <%= form.label :rule %>
        <%= form.select :rule, Badge.rules.values.map {|rule| [rule.titleize, rule]}, id: :badge_rule, class: 'form-control' %>

      </div>
      <%= form.submit "Создать", class: 'btn btn-primary'  %>
    <% end %>
  </div>
</div>

app/views/admin/badges/index.html.erb
<h1>Список бэйджев</h1>
<%= link_to t('.create_badge'), new_admin_badge_path %>

<%= render 'shared/errors', resource: @test %>

<table class="table table-striped">
  <tr class="table-primary">
    <th class="sort-by-title pointer">
      <%= t('.title') %>
      <%= octicon 'arrow-up', class: 'text-success hide' %>
      <%= octicon 'arrow-down', class: 'text-success hide' %>
    </th>
    <th><%= t('.image') %></th>
    <th><%= t('.rule') %></th>
    <th><%= t('.users') %></th>
    <th colspan="3"><%= t('.actions') %></th>
  </tr>
  <%= render @badges %>
</table>

<%= link_to t('.back'), :root %>

app/views/admin/badges/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('.back'), admin_badges_path %>

app/views/admin/badges/show.html.erb
<h1><%= t('.badge') %>: <%= @badge.title %></h1>
<%= link_to t('.create_badge'), new_admin_badge_path %>

<table class="table table-striped">
  <tr class="table-primary">
    <th><%= t('.title') %></th>
    <th><%= t('.image') %></th>
    <th><%= t('.rule') %></th>
    <th><%= t('.users') %></th>
    <th colspan="3"><%= t('.actions') %></th>
  </tr>
  <%= render @badge %>
</table>

<br>

<%= link_to t('.back'), admin_badges_path %>

app/views/badges/show.html.erb
<% if @badges %>
  <table class="table table-striped">
    <tr class="table-primary">
      <th><%= t('.title') %></th>
      <th><%= t('.image') %></th>
      <th><%= t('.rule') %></th>
    </tr>
    <% @badges.each do |badge| %>
      <tr>
        <td class="title align-middle"><%= badge.title %></td>
        <td class="id align-middle"><img src="<%= badge.url_image %>" width="70" height="70"></td>
        <td class="id align-middle"><%= badge.rule %></td>
      </tr>
    <% end %>
  </table>

  <br>

  <%= link_to t('.back'), root_path %>
<% else %>
  <h1>Бэйджи еще не созданы</h1>
<% end %>