config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  devise_for :users, path: :gurus, path_names: {sign_in: :login, sign_out: :logout},
             controllers: { registrations: 'registrations', sessions: 'sessions' }

  resource :user_badges, only: %i[show]
  resource :badges, only: %i[show]

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, shallow: true, only: %i[show index]
    resources :badges, shallow: true
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feed_backs

end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  ANSWERS_LIMIT_ON_QUESTION = 4

  belongs_to :question
  scope :correct, -> { where(correct: true) }

  validates :text, presence: true
  validate :validate_answers_limit_on_question, on: :create

  private

  def validate_answers_limit_on_question
    errors.add('Answers on question too many') if question.answers.count >= ANSWERS_LIMIT_ON_QUESTION
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges

  enum rule: { success_backend: 'successful_completion_of_all_tests_from_the_Backend_category',
               success_on_first_try: 'passing_the_test_successfully_on_the_first_try',
               success_certain_level: 'successful_completion_of_all_tests_of_a_certain_level'
  }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests
  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/feed_back.rb
class FeedBack < ApplicationRecord
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
require 'date'

class Test < ApplicationRecord
  has_many :test_passages
  has_many :users, through: :test_passages

  belongs_to :category
  has_many :questions, dependent: :destroy

  belongs_to :author, class_name: 'User', foreign_key: :author_id

  scope :by_category_name, ->(category) { joins(:category).where(categories: { title: category }) }

  scope :success_tests, -> { joins(:test_passages).where('test_passages.success = ?', true) }

  def self.by_category_name_arr(category)
    by_category_name(category).order(id: :desc).pluck('tests.title')
  end

  scope :simple_level, -> { where(level: 0..1) }
  scope :average_level, -> { where(level: 2..4) }
  scope :high_level, -> { where(level: 5..Float::INFINITY) }

  scope :by_level, ->(level) { where(level: level) }

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { greater_than_or_equal_to: 1 }

  def timer_on_seconds
    if timer
      dt = timer.to_time
      dt.hour * 3600 + dt.min * 60 + dt.sec
    end
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATE_PERCENT = 85

  belongs_to :user
  belongs_to :test, dependent: :delete
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :next_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def count_questions
    self.test.questions.where("id <= ?", current_question.id).count
  end

  def percentage_result
    100.0 / test.questions.count * correct_questions
  end

  def success?
    percentage_result >= SUCCESS_RATE_PERCENT
  end

  def time_is_left?
    return unless test.timer

    seconds = test.timer_on_seconds
    DateTime.now <= self.created_at + seconds
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first unless self.completed?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         # :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :gists
  has_many :tests, through: :test_passages
  has_many :author_tests, class_name: 'Test', foreign_key: :author_id

  has_many :user_badges
  has_many :badges, through: :user_badges

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end

end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/users_test.rb
class UsersTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def this_year
    Date.today.year
  end

  def github_url(author, repo)
    "https://github.com/#{author}/#{repo}"
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feed_backs_helper.rb
module FeedBacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      'Создать вопрос'
    else
      'Редактировать вопрос'
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def display_timer(test)
    test.timer ? test.timer.strftime("%H:%M:%S") : "--:--"
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Panel | TestGuru</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<%= render 'shared/nav' %>
<%= render 'shared/flash' %>

<%= yield %>

<%= render 'shared/footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="with=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/nav' %>

    <div class="container">
      <%= render 'shared/flash' %>

      <%= yield %>

      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= t('.header', count: resource.errors.count) %>: </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <div class="alert-danger"><%= message %></div>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "flash #{key} alert-info" %>
<% end %>

app/views/shared/_footer.html.erb
<article>

  <h1>----------</h1>

  <footer>
    <p><%= t('.author') %>: Platonov Oleg</p>
    <p><%= t('.project') %>: <a href="<%= github_url('pythoneyron', 'test_guru') %>" target="_blank">Test Guru</a></p>
    <p><%= t('.description') %> <a href="https://thinknetica.com/" target="_blank">Thinknetica</a></p>
    <p>© <%= this_year %> Test Guru</p>
  </footer>
</article>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <h2 class="header">
    <% if current_user && current_user.admin? %>
      <%= link_to 'Admin TestGuru', admin_tests_path, class: 'navbar-brand' %>
      <%= link_to 'На главную', root_path, class: 'navbar-brand' %>
    <% else %>
      <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
    <% end %>
  </h2>

  <span class="navbar-text">
    <%= link_to 'Форма обратной связи', new_feed_back_path %> |
    <% if user_signed_in? %>
      <%= t('.welcome') %>, <b><%= current_user.email %></b> Guru |
      <%= link_to t('.sign_out'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.sign_in'), :new_user_session %> |
      <%= link_to t('.registration'), :new_user_registration %>
    <% end %>
  </span>
</nav>